from setuptools import setup, find_packages

setup(
    name='llm_blender_mps',
    version='0.0.3',
    description='LLM-Blender with MPS backend',
    author='Dongfu Jiang & Fangyuan Yu',
    author_email='dongfu.jdf@gmail.com  & fangyuan.yu@temus.com',
    packages=find_packages(),
    url='https://github.com/fangyuan-ksgk/PairRM-with-mps',
    install_requires=[
        'transformers>=4.31.0',
        'datasets',
        'torch',
        'wget',
        'pycocoevalcap',
        'spacy',
        'prettytable',
        'fairscale',
        'evaluate',
        'bert_score',
        'cpm_kernels',
        'sentencepiece',
        'fschat',
        'numpy',
        'tabulate',
        'nltk',
        'scipy',
        'matplotlib',
        'pandas',
        'scikit-learn',
        'protobuf<=3.20.1',
        'wandb',
        'sacrebleu',
        'dataclasses-json',
        'accelerate',
        'safetensors',
        'gradio',
        'openai'
        # 'bitsandbytes',
        # 'openai',
        # 'peft',
        # 'BLEURT @ git+https://github.com/google-research/bleurt.git@cebe7e6f996b40910cfaa520a63db47807e3bf5c',
        # 'deepspeed',
        # 'rouge_score',
    ],
)
